export enum coachNoteErrors {
  NOT_ASSIGNED_COCHEE = 'NOT_ASSIGNED_COCHEE',
  NOT_EXISTING_COCHEES = 'NOT_EXISTING_COCHEES',
  SUSPENDED_COACHEE = 'SUSPENDED_COACHEE',
  NOT_ALLOWED_TO_UPDATE = 'NOT_ALLOWED_TO_UPDATE',
}
