export enum CoachingError {
  NO_SAT_REALIZED = 'NO_SAT_REALIZED',
  NOT_OWNER = 'NOT_OWNER',
  NOT_ADMIN = 'NOT_ADMIN',
  NOT_FOUND_COACHEE = 'NOT_FOUND_COACHEE',
  NOT_ALLOWED_ACTION = 'NOT_ALLOWED_ACTION',
  UNAUTHORIZED = 'UNAUTHORIZED',
  //
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ALREADY_IN_ORGANIZATION = 'ALREADY_IN_ORGANIZATION',
  ORGANIZATION_ID_REQUIRED = 'ORGANIZATION_ID_REQUIRED',
  WRONG_MEDIA_EXTENSION = 'WRONG_MEDIA_EXTENSION',
  ERROR_UPLOADING_MEDIA = 'ERROR_UPLOADING_MEDIA',
  ERROR_DELETING_MEDIA = 'ERROR_DELETING_MEDIA',
  //
  ACTION_NOT_ALLOWED = 'ACTION_NOT_ALLOWED',
}
