export enum CoacheeEditErrors {
  NOT_OWNER = 'NOT_OWNER',
  NOT_ADMIN = 'NOT_ADMIN',
  NOT_FOUND_COACHEE = 'NOT_FOUND_COACHEE',
  COACHEE_FROM_ANOTHER_ORGANIZATION = 'COACHEE_FROM_ANOTHER_ORGANIZATION',
}
