export enum CoachingErrorEnum {
  NO_COACH_ASSIGNED = 'NO_COACH_ASSIGNED',
  NO_COACHEE_PROFILE = 'NO_COACHEE_PROFILE',
  NO_COACH_PROFILE = 'NO_COACH_PROFILE',
  NO_SAT_REALIZED = 'NO_SAT_REALIZED',
  NOT_ENOUGH_COACHES = 'NOT_ENOUGH_COACHES',
  MAX_COACH_SUGGESTIONS_REACHED = 'MAX_COACH_SUGGESTIONS_REACHED',
}
