export enum CoacheeErrors {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ALREADY_IN_ORGANIZATION = 'ALREADY_IN_ORGANIZATION',
  ORGANIZATION_ID_REQUIRED = 'ORGANIZATION_ID_REQUIRED',
  NOT_OWNER = 'NOT_OWNER',
  NOT_ADMIN = 'NOT_ADMIN',
  NOT_FOUND_COACHEE = 'NOT_FOUND_COACHEE',
  COACHEE_FROM_ANOTHER_ORGANIZATION = 'COACHEE_FROM_ANOTHER_ORGANIZATION',
  COACHEE_PROFILE_SUSPENDED = 'COACHEE_PROFILE_SUSPENDED',
}
