export enum CoacheeEditErrors {
  NOT_OWNER_ORGANIZATION_EDIT_COACHEE = 'NOT_OWNER_ORGANIZATION_EDIT_COACHEE',
  COACHEE_FROM_ANOTHER_ORGANIZATION = 'COACHEE_FROM_ANOTHER_ORGANIZATION',
  NOT_FOUND_COACHEE = 'NOT_FOUND_COACHEE',
}
