export enum coachEditErrors {
  NOT_EXISTING_COACH = 'NOT_EXISTING_COACH',
  WRONG_IMAGE_EXTENSION = 'WRONG_IMAGE_EXTENSION',
  ERROR_UPLOADING_IMAGE = 'ERROR_UPLOADING_IMAGE',
  ERROR_DELETING_IMAGE = 'ERROR_DELETING_IMAGE',
}
