export enum CoacheeEditErrors {
  NOT_OWNER = 'NOT_OWNER',
  NOT_ADMIN = 'NOT_ADMIN',
  NOT_FOUND_COACHEE = 'NOT_FOUND_COACHEE',
  COACHEE_FROM_ANOTHER_ORGANIZATION = 'COACHEE_FROM_ANOTHER_ORGANIZATION',
  NOT_EXISTING_COACHEE = 'NOT_EXISTING_COACHEE',
  WRONG_IMAGE_EXTENSION = 'WRONG_IMAGE_EXTENSION',
  ERROR_UPLOADING_IMAGE = 'ERROR_UPLOADING_IMAGE',
}
