export enum SuggestedCoachErrors {
  NOT_ENOUGH_COACHES = 'NOT_ENOUGH_COACHES',
  MAX_COACH_SUGGESTIONS_REACHED = 'MAX_COACH_SUGGESTIONS_REACHED',
  COACH_NOT_SUGGESTED = 'COACH_NOT_SUGGESTED',
  COACHEE_ALREADY_HAS_COACH = 'COACHEE_ALREADY_HAS_COACH',
}
