export enum AgendaErrorsEnum {
  APPOINTMENT_NOT_RELATED_TO_AGENDA = 'APPOINTMENT_NOT_RELATED_TO_AGENDA',
  APPOINTMENT_ACCOMPLISHED = 'APPOINTMENT_ACCOMPLISHED',
  BAD_DATE_INPUT = 'BAD_DATE_INPUT',
  COACH_HAS_NO_AVAILABILITY = 'COACH_HAS_NO_AVAILABILITY',
  DAY_ALREADY_CONFIGURED = 'DAY_ALREADY_CONFIGURED',
  EXCEEDS_MAXIMUN_APPOINTMENT_DISTANCE = 'EXCEEDS_MAXIMUN_APPOINTMENT_DISTANCE',
  EXCEEDS_MAXIMUN_APPOINTMENT_PER_MONTH = 'EXCEEDS_MAXIMUN_APPOINTMENT_PER_MONTH',
  LESS_THAN_MINIMUN_SESSION_DURATION = 'LESS_THAN_MINIMUN_SESSION_DURATION',
  COACH_TEMPORARILY_OUT_OF_SERVICE = 'COACH_TEMPORARILY_OUT_OF_SERVICE',
  COACHEE_NOT_ASSIGNED_TO_COACH = 'COACHEE_NOT_ASSIGNED_TO_COACH',
}
