export enum editOrganizationError {
  USER_DOES_NOT_HAVE_ORGANIZATION = 'USER_DOES_NOT_HAVE_ORGANIZATION',
  USER_IS_NOT_ORGANIZATION_ADMIN = 'USER_DOES_IS_NOT_ORGANIZATION_ADMIN',
  USER_IS_NOT_ORGANIZATION_OWNER = 'USER_DOES_IS_NOT_ORGANIZATION_OWNER',
}
