export enum editOrganizationError {
  USER_DOES_NOT_HAVE_ORGANIZATION = 'USER_DOES_NOT_HAVE_ORGANIZATION',
  USER_IS_NOT_ORGANIZATION_ADMIN = 'USER_DOES_IS_NOT_ORGANIZATION_ADMIN',
  USER_IS_NOT_ORGANIZATION_OWNER = 'USER_DOES_IS_NOT_ORGANIZATION_OWNER',
  WRONG_IMAGE_EXTENSION = 'WRONG_IMAGE_EXTENSION',
  ERROR_UPLOADING_IMAGE = 'ERROR_UPLOADING_IMAGE',
  USER_CAN_ONLY_EDIT_OWN_ORGANIZATION = 'USER_CAN_ONLY_EDIT_OWN_ORGANIZATION',
  COACHEE_CAN_ONLY_EDIT_OWN_ORGANIZATION = 'COACHEE_CAN_ONLY_EDIT_OWN_ORGANIZATION',
}
