import { registerEnumType } from '@nestjs/graphql';

export enum AnswerDimensions {
  CW = 'IMPLANTER',
  CH = 'COORDINATOR',
  ME = 'EVALUATOR',
  PL = 'CREATIVE',
  RI = 'RESOURCE_INVESTIGATOR',
  TW = 'TEAM_WORKER',
  CF = 'FINISHER',
  SH = 'DYNAMIC',
  IMPROVE_PRODUCTIVITY = 'IMPROVE_PRODUCTIVITY',
  IMPROVE_SOCIAL_RELATIONS = 'IMPROVE_SOCIAL_RELATIONS',
  IMPROVE_LIVE_WORK_BALANCE = 'IMPROVE_LIVE_WORK_BALANCE',
  IMPROVE_WORK_RELATIONS = 'IMPROVE_WORK_RELATIONS',
  IMPROVE_LEADERSHIP = 'IMPROVE_LEADERSHIP',
  IMPROVE_COMMUNICATION_SKILLS = 'IMPROVE_COMMUNICATION_SKILLS',
  IMPROVE_TECH_SKILLS = 'IMPROVE_TECH_SKILLS',
  IMPROVE_INTERPERSONAL_SKILLS = 'IMPROVE_INTERPERSONAL_SKILLS',
  IMPROVE_INTRAPERSONAL_SKILLS = 'IMPROVE_INTRAPERSONAL_SKILLS',
}

registerEnumType(AnswerDimensions, {
  name: 'AnswerDimensions',
});
