export enum DiagnosticsEnum {
  OUTSTANGIND_COMMUNICATION = 'OUTSTANGIND_COMMUNICATION',
  BELOW_AVEGARE_COMMUNICATION = 'BELOW_AVEGARE_COMMUNICATION',
  LOW_SKILL_COMMUNICATION = 'LOW_SKILL_COMMUNICATION',
  IN_AVERAGE_OF_SOME_COMMUNICATION_SKILL = 'IN_AVERAGE_OF_SOME_COMMUNICATION_SKILL',
  LOW_AVERAGE_OF_SOME_COMMUNICATION_SKILL = 'LOW_AVERAGE_OF_SOME_COMMUNICATION_SKILL',
}
