import { registerEnumType } from '@nestjs/graphql';

export enum QuestionDimentions {
  GENERAL = 'GENERAL',
  //Communication
  UPWARD_COMMUNICATION = 'UPWARD_COMMUNICATION',
  DOWNWARD_COMMUNICATION = 'DOWNWARD_COMMUNICATION',
  HORIZONTAL_COMMUNICATION = 'HORIZONTAL_COMMUNICATION',
  // LeaderShip
  TRANSFORMATIONAL_LEADERSHIP = 'TRANSFORMATIONAL_LEADERSHIP',
  CORRECTIVE_AVOIDANT_LEADERSHIP = 'CORRECTIVE_AVOIDANT_LEADERSHIP',
  TRANSACTIONAL_LEADERSHIP = 'TRANSACTIONAL_LEADERSHIP',
  // Teamwork
  IMPLANTER = 'IMPLANTER',
  COORDINATOR = 'COORDINATOR',
  EVALUATOR = 'EVALUATOR',
  CREATIVE = 'CREATIVE',
  RESOURCE_INVESTIGATOR = 'RESOURCE_INVESTIGATOR',
  TEAM_WORKER = 'TEAM_WORKER',
  FINISHER = 'FINISHER',
  //Emotional State
  SADNESS = 'SADNESS',
  ANXIETY = 'ANXIETY',
  ANGER = 'ANGER',
  JOY = 'JOY',
  // Life Purpose
  PERCEPTION_OF_LIFE = 'PERCEPTION_OF_LIFE',
  EXPERIENCE_OF_LIFE = 'EXPERIENCE_OF_LIFE',
  // HEALT
  PHYSICAL_ACTIVITY = 'PHYSICAL_ACTIVITY',
  DIET = 'DIET',
  REST_AND_SLEEP = 'REST_AND_SLEEP',
  MENTAL_RELAXATION = 'MENTAL_RELAXATION',
  PERSONAL_AND_PROFESIONAL_BALANCE = 'PERSONAL_AND_PROFESIONAL_BALANCE',
  // Getting Into Action
  SKILL_IMPROVEMENT = 'SKILL_IMPROVEMENT',
}

registerEnumType(QuestionDimentions, {
  name: 'QuestionDimentions',
});
