name: Node.js CI

on:
  pull_request:
    branches: [development, QA, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      - name: Install dependencies
        run: yarn
      - name: Running Lint
        run: yarn lint
      - name: Running Tests
        run: yarn test
