export const ExcludedFieldsFromRelations = [
  'coachAgendaAvailabilityRange',
  'coachAgendaDayAvailableHours',
  'availableHours',
  'coachProfilePicture',
  'coachProfileVideo',
  'coacheeProfilePicture',
  'organizationProfilePicture',
  'satBasicTranslations',
  'satBasicAnswerTranslations',
  'satBasicQuestionTranslations',
  'satBasicSectionTranslations',
  'satReportResult',
  'coachingSessionFeedbackCoacheeFeedback',
  'coachingSessionFeedbackCoachFeedback',
  'feedbackQuestions',
];
